import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Web3SignerContextProvider } from "@/context/web3";
import { Navigations } from "@/app/_components/common/Navigations";
import {twMerge} from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={'h-full'}>
			<body className={twMerge(inter.className, 'h-full')}>
				<Web3SignerContextProvider>
					<div className={"flex h-full"}>
						<aside className={'h-full border-r py-10 px-4 flex flex-col justify-start'}>
							<h1 className={'text-2xl font-bold mb-10'}>App Title</h1>
							<Navigations />
						</aside>
						<main className={'p-10'}>{children}</main>
					</div>
				</Web3SignerContextProvider>
			</body>
		</html>
	);
}
